remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-github-metadata

title: Kerb Writeups
author: Kerburenthusiasm
description: A blog to host my CTF writeups (mostly HTBs) and other security-related interests.

url: "https://kerburenthusiasm.github.io"
baseurl: "/kerbwriteups"

markdown: kramdown
permalink: /:year/:month/:day/:title/

collections:
  ctfs:
    output: true
    permalink: /ctf/:title/
  others:
    output: true
    permalink: /others/:title/
  tools:
    output: true
    permalink: /tools/:title/

exclude:
  - .github/
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
